# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181118_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='userid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
